---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  - monitoring.cloud.sap
  resources:
  - deployments
  - vropsexporters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.cloud.sap
  resources:
  - vropsexporters/finalizers
  verbs:
  - '*'
- apiGroups:
  - monitoring.cloud.sap
  resources:
  - vropsexporters/status
  verbs:
  - get
  - patch
  - update
